default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: training_chat_development

test:
  <<: *default
  database: training_chat_test

production:
  <<: *default
  database: training_chat_production